driver:
  name: docker
  use_sudo: false
  customize: memory 1048
provisioner:
  name: chef_zero
verifier:
  name: inspec
  sudo_command: . /etc/profile;
platforms:
- name: ubuntu-1404
#  - name: centos-7.2
suites:
- name: default
  run_list:
  - recipe[star::default]
  attributes:
